services:
  video-search:
    image: twamix/video-search:latest
    container_name: video-search-search-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
